### ISSUE TITLE
Network byte order

### ISSUE THREAD

**Issue by tsenart** [RobThree/NUlid#1]
Hello there,

I'm confused regarding the byte order of the time components in the ULID. The original project states the following:

 	   The components are encoded as 16 octets.
	   Each component is encoded with the MSB first (network byte order).

	   0                   1                   2                   3
	    0 1 2 3 4 5 6 7 8 9 0 1 2 3 4 5 6 7 8 9 0 1 2 3 4 5 6 7 8 9 0 1
	   +-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+
	   |                      32_bit_uint_time_low                     |
	   +-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+
	   |     16_bit_uint_time_high     |       16_bit_uint_random      |
	   +-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+
	   |                       32_bit_uint_random                      |
	   +-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+
	   |                       32_bit_uint_random                      |
	   +-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+

What I read from the above would result in the following diff in this function:

```diff
diff --git a/NUlid/Ulid.cs b/NUlid/Ulid.cs
index 70fe351..3639faa 100644
--- a/NUlid/Ulid.cs
+++ b/NUlid/Ulid.cs
@@ -147,7 +147,7 @@ namespace NUlid
         private static byte[] DateTimeOffsetToByteArray(DateTimeOffset value)
         {
             var mb = BitConverter.GetBytes(value.ToUnixTimeMilliseconds());
-            return new[] { mb[5], mb[4], mb[3], mb[2], mb[1], mb[0] };                                  // Drop byte 6 & 7
+            return new[] { mb[2], mb[3], mb[4], mb[5], mb[0], mb[1] };                                  // Drop byte 6 & 7
         }

         private static DateTimeOffset ByteArrayToDateTimeOffset(byte[] value)
```

Can you help me understand this please? Thank you :-)

**Comment by RobThree** [comment]
Help you understand what? I'm sorry, I don't understand the question? What is de diff from? Are those changes you made? Or...?

**Comment by tsenart** [comment]
> Each component is encoded with the MSB first (network byte order).

We have two components: **32_bit_uint_time_low** and **16_bit_uint_time_high**

The way I understand that diagram means the byte order in `DateTimeOffsetToByteArray` should be
`{ mb[2], mb[3], mb[4], mb[5], mb[0], mb[1] }` instead of
`{ mb[5], mb[4], mb[3], mb[2], mb[1], mb[0] }`, where the first *4* bytes represent the initial **32_bit_uint_time_low** and the next *2* represent the **16_bit_uint_time_high**.

Am I reading that diagram the wrong way?

**Comment by RobThree** [comment]
NUlid simply follows the original implementation [and tests](https://github.com/alizain/ulid/blob/master/test.js) of the ULID. If it were `mb[2], mb[3], mb[4], mb[5], mb[0], mb[1]` the tests would've failed. The diagram maybe open for interpretation / confusing but the testcases resolve that issue I guess?

**Comment by tsenart** [comment]
Yes, I understand that. However, the binary implementation was left out in the original project. I'd like @alizain's input on this so we can come to a conclusion.

**Comment by tsenart** [comment]
@RobThree: FYI, I've reused your optimized unrolled loops: http://github.com/tsenart/go-ulid

**Comment by alizain** [comment]
I had intended it to be (in pseudocode):

```javascript
/* effectively a 48bit integer */
new Integer [bytes[5], bytes[4], bytes[0], bytes[1], bytes[2], bytes[3]]
```

Though I must admit, I may have poorly specified this. If it doesn't make sense, I'd be grateful for feedback and suggestions.

**Comment by tsenart** [comment]
@alizain: Right, that's how I interpreted it as per-spec, but I'm not sure it's better that way. If we keep the relative byte order as implemented in this repo and mine, we can lexicographically compare the binary UUIDs as well as  the textual versions. Or perhaps I'm not seeing how that property would be maintained with that byte order.

**Comment by alizain** [comment]
Ah, I see. So in that case, the byte order would be:

```javascript
new Integer [bytes[5], bytes[4], bytes[3], bytes[2], bytes[1], bytes[0]]
```

And the diagram would look something like so:

```
   0                   1                   2                   3
    0 1 2 3 4 5 6 7 8 9 0 1 2 3 4 5 6 7 8 9 0 1 2 3 4 5 6 7 8 9 0 1
   +-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+
   |    bytes[0]   |    bytes[1]   |    bytes[2]   |    bytes[3]   |
   +-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+
   |    bytes[4]   |    bytes[5]   |       16_bit_uint_random      |
   +-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+
   |                       32_bit_uint_random                      |
   +-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+
   |                       32_bit_uint_random                      |
   +-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+
```

In which case, we're following **least significant byte** order, no?

**Comment by tsenart** [comment]
@alizain: Depends on the CPU architecture. Intel convention is LSB or Little endian. An `uint64` such as our Unix millisecond timestamp is laid out in memory as such:

```
Little endian (LSB first): 0x1122334455667788 -> [0x88, 0x77, 0x66, 0x55, 0x44, 0x33, 0x22, 0x11]
Big endian (MSB first):    0x1122334455667788 -> [0x11, 0x22, 0x33, 0x44, 0x55, 0x66, 0x77, 0x88]
```

As this repository implements, I think we should just make the first 6 bytes of the ULID the first 6 MSB of the Unix time in miliseconds.

**Comment by tsenart** [comment]
I think the following captures what I explained.
```
   0                   1                   2                   3
    0 1 2 3 4 5 6 7 8 9 0 1 2 3 4 5 6 7 8 9 0 1 2 3 4 5 6 7 8 9 0 1
   +-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+
   |                      32_bit_uint_time_high                    |
   +-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+
   |     16_bit_uint_time_low     |       16_bit_uint_random       |
   +-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+
   |                       32_bit_uint_random                      |
   +-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+
   |                       32_bit_uint_random                      |
   +-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+
```

**Comment by alizain** [comment]
Okay, sounds great, thank you for going through it.

If there are no objections, @tsenart, would you like to submit a PR to the original repo reflecting this understanding?

**Comment by tsenart** [comment]
@alizain: Sure! I'll do that. Just for some more visual hints, here's a comparison of the first 16 ULIDs with no entropy starting from Unix time zero with both MSB and LSB encoding.

#### MSB
```
time       entropy                             
0000000000 0000000000000000
0000000001 0000000000000000
0000000002 0000000000000000
0000000003 0000000000000000
0000000004 0000000000000000
0000000005 0000000000000000
0000000006 0000000000000000
0000000007 0000000000000000
0000000008 0000000000000000
0000000009 0000000000000000
000000000A 0000000000000000
000000000B 0000000000000000
000000000C 0000000000000000
000000000D 0000000000000000
000000000E 0000000000000000
000000000F 0000000000000000
```

#### LSB
```
time       entropy                             
0000000000 0000000000000000
0100000000 0000000000000000
0200000000 0000000000000000
0300000000 0000000000000000
0400000000 0000000000000000
0500000000 0000000000000000
0600000000 0000000000000000
0700000000 0000000000000000
0800000000 0000000000000000
0900000000 0000000000000000
0A00000000 0000000000000000
0B00000000 0000000000000000
0C00000000 0000000000000000
0D00000000 0000000000000000
0E00000000 0000000000000000
0F00000000 0000000000000000
```

**Comment by RobThree** [comment]
:+1:
