### ISSUE TITLE
Duplicate Ulid generated (serious)

### ISSUE THREAD

**Issue by oliverjanik** [RobThree/NUlid#12]
This is not a joke. Here's the setup:

1) The project is a IIS Asp.net application (WebAPI 2) running on .net 4.6
2) Recycle app pool (or just restart the site in IIS)
3) hit a request that uses Ulid.NewUlid() 2 times, (in my case this is primary key generation)

So what's happening is that the 2 requests are blocked until the Startup has finished after AppPool recycle. After startup finishes both requests are let through the gate. I'm unsure about the internal mechanism might be a semaphore.

Both requests call `Ulid.NewUlid()` at the same millisecond, so the first part is identical. But how come the random part is the same? Is there a data race in this library?

Looking underneath it uses `BaseUlidRng.DEFAULTRNG` which initalises a static `RNGCryptoServiceProvider` could this be the data race?

**Comment by oliverjanik** [comment]
I think I found it. 

There's only ever 1 instance of `CSUlidRng` created:
```
public static readonly IUlidRng DEFAULTRNG = new CSUlidRng();
```

This class has an internal buffer which is shared:
```
    public class CSUlidRng : BaseUlidRng
    {
        private static readonly RNGCryptoServiceProvider _rng = new RNGCryptoServiceProvider();

        private readonly byte[] _buffer = new byte[10];

        public override byte[] GetRandomBytes(DateTimeOffset dateTime)
        {
            _rng.GetBytes(_buffer);
            return _buffer;
        }
    }
```
So 2 quick successive calls to `GetRandomBytes` will have a data race right there between `_rng.GetBytes(_buffer)` and returning the buffer.

The solutions seems to be a new allocation each time. Could be just stackalloc.

**Comment by RobThree** [comment]
The `SimpleUlidRNG` has the same problem.

> Could be just stackalloc.

What would you propose? Wouldn't this be the simplest fix?

	public override byte[] GetRandomBytes(DateTimeOffset dateTime)
	{
		var buffer = new byte[RANDLEN];
		_rng.GetBytes(buffer);
		return buffer;
	}

**Comment by oliverjanik** [comment]
I was thinking of using [stackalloc](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/operators/stackalloc) to make sure no heap allocation is done.

But your buffer gets returned so that may not be an option. 

I have not investigated that further. Your proposal definitely fixes the problem.

**Comment by RobThree** [comment]
> Your proposal definitely fixes the problem.

Yes, but it will also do an allocation each time a ULID is generated. Not that I have heavily optimized the ULID library anyway, but I was thinking of creating a 'pool' of buffers and use an index into the pool which is atomically incremented (and 'wrapped around') every call. As long as the pool is big enough (ideally greater or equal to the number of generators) that should avoid allocations and race conditions. However, we don't know what would be the ideal pool size ahead of time. We could use some magic number like 10 or 1000 (* 10 bytes, so it shouldn't be that bad) which reduces this race condition to at least a factor of 10 or 1000 from what it was. But theoretically it's still possible.

> I was thinking of using stackalloc to make sure no heap allocation is done.

I understand but that would change the method signature to `unsafe` and would also require me to compile with `/unsafe` and I have no idea if that would be a breaking change (probably?).

Oh, by the way, thanks for noticing and reporting!

**Comment by oliverjanik** [comment]
Correctness above speed IMO. A Nuget update that fixes the data race would be much appreciated. Optimisations can be applied later.

As I said I have not looked into removing allocations deeply. If you allocate a constant length buffer that might be on the stack automatically. I'd have to run experiments or read the spec :-D

**Comment by RobThree** [comment]
I'm running a few experiments now; whatever the outcome, I will publish a fix today, be it optimized or not.

**Comment by oliverjanik** [comment]
Fantastic! Cheers!

**Comment by RobThree** [comment]
[1.4.1](https://www.nuget.org/packages/NUlid/1.4.1) should fix it.
