### ISSUE TITLE
Move repository under the ulid organization

### ISSUE THREAD

**Issue by grantcarthew** [RobThree/NUlid#14]
https://github.com/ulid

**Comment by RobThree** [comment]
I wouldn't really mind, but [none of the other implementations](https://github.com/ulid/spec#implementations-in-other-languages) are, and as far as I can see, you didn't bring this up on any of them. I can see why you'd want this (probably) but mind if I ask why this one only?

**Comment by grantcarthew** [comment]
It's just a suggestion Rob. Kill it if you don't want to.

I found this repo when searching for PostgreSQL + ulid.

Infact, forget about it. Sorry to waste your time.

**Comment by RobThree** [comment]
You didn't waste my time. I was/am just curious 😉
