### ISSUE TITLE
multiple machines for the same time.incrementation

### ISSUE THREAD

**Issue by NckGroup** [RobThree/NUlid#26]
I have seen that the MonotonicUlidRng implements monotonic incrementation within a single machine for the same time. I would like to know if it supports monotonic incrementation across multiple machines for the same time.

**Comment by RobThree** [comment]
It doesn't but it's also not defined in the ULID spec how that'a supposed to work. Honestly, if at all possible I'd look into [IdGen](https://github.com/RobThree/IdGen) which will likely be more suited to your needs.

**Comment by NckGroup** [comment]
OK, thanks.
