### ISSUE TITLE
Nuget package do not work for .NET 4.5.2

### ISSUE THREAD

**Issue by mgnslndh** [RobThree/NUlid#8]
It is possible to add the nuget package to a .NET 4.5.2 project but since the library is for .NET 4.6 it will not be added to the project references. This is really confusing. I guess it is possible to add some kind of .NET framework compatibility requirement to the package so that projects with < .NET 4.6 can not install the package.

**Comment by mgnslndh** [comment]
Did some poking around and it seems like the use of `ToUnixTimeMilliseconds()` and `FromUnixTimeMilliseconds()` requires .NET 4.6

It would be nice to also target earlier version of the framework and in that case add extension methods for those missing methods.

**Comment by RobThree** [comment]
Oh, that's my bad I guess. It's pretty trivial to implement those functions. I'll try to add them / fix the NuGet package upcoming week.

**Comment by RobThree** [comment]
Should work across .Net 4.5 and up and also for .Net Core and .Net Standard (see 4878f942455631b1f6844163dca5bc34b6600471)
